{
 "title": "Cours Apple",
 "time": { "from": "2020-03-17T23:00:00.000Z", "to": "2020-03-18T22:59:59.000Z" },
 "panels": [
  {
   "title": "Open-Close-Low-Higth Cours Apple mars 2020-mars 2021",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  Close,\n  Open,\n  Hight,\n  Low\nFROM data_cours_apple\nWHERE\n  $__timeFilter(Date)\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Cours Apple mars 2021",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  Volume,\n  Hight,\n  Low,\n  Open,\n  Close\nFROM data_cours_apple\nWHERE\n  $__timeFilter(Date)\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Volume Apple  2020-2021",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  Volume\nFROM data_cours_apple\nWHERE\n  $__timeFilter(Date)\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Cours Apple mars 2020",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  Volume,\n  Hight,\n  Low,\n  Open,\n  Close\nFROM data_cours_apple\nWHERE\n  $__timeFilter(Date)\nORDER BY Date"
    }
   ]
  }
 ]
}